### ISSUE TITLE
tensorflow version

### ISSUE THREAD

**Issue by xzdong-2019** [cl-tohoku/bert-japanese#1]
hi，
     I have a question about tensorflow version. when installing tensorflow-gpu==1.1.14,  cannot find the version,  I can use the version 1.14.0 but not using gpu. is the version  1.1.14? Thanks for your help.

**Comment by singletongue** [comment]
Hi,

Sorry, it is simply a typo. The correct version number is 1.14.0. Thank you for your comment!

**Comment by xzdong-2019** [comment]
thanks， i change my machine and run it.
