### ISSUE TITLE
Will tokenizer remove stopwords?

### ISSUE THREAD

**Issue by HeroadZ** [cl-tohoku/bert-japanese#11]
I'm using the hugging face's japanese tokenizer. 
The name is ''cl-tohoku/bert-base-japanese-whole-word-masking'. Will it remove stopwords automatically in tokenizer and model?

**Comment by singletongue** [comment]
No, as the original BERT models don't.

**Comment by HeroadZ** [comment]
I see. Thank you very much. 
And one more question, why can't this tokenizer recognize 'ヨーグルト'? It surprises me cause this word is simple in my opinion.

**Comment by singletongue** [comment]
With the tokenizer for `"cl-tohoku/bert-base-japanese-whole-word-masking"`, "ヨーグルト" should be tokenized into subwords.
It is because the word is not so frequent in the training corpus (Wikipedia).

```py
>>> from transformers import BertJapaneseTokenizer
>>> tokenizer = BertJapaneseTokenizer.from_pretrained('cl-tohoku/bert-base-japanese-whole-word-masking')
>>> tokenizer.tokenize('ヨーグルト')
['ヨー', '##グル', '##ト']
```

**Comment by HeroadZ** [comment]
Thank you for detailed explanation！
