### ISSUE TITLE
About Pre-Training times

### ISSUE THREAD

**Issue by sezai-rdc** [cl-tohoku/bert-japanese#16]
Nice to meet you.
I will be using this gitlab code to pre-train with CloudTPU (v3-8).
I have only done 1000 steps and it was going to take me 4 days to implement 1000000 steps.
How many hours (days) did this gitlab pre-training take using CloudTPU(v3-8)?

**Comment by singletongue** [comment]
The pretraining of each distributed model took approx. 7 days to finish 1,000,000 steps in v3-8 Cloud TPUs.
It should largely depend on the size of pretraining corpus.

**Comment by sezai-rdc** [comment]
Thank you.
By the way, can you tell me how much it cost you to use it for 7 days?

**Comment by singletongue** [comment]
Actually, I was able to use TPUs for free thanks to the [TensorFlow Research Cloud](https://www.tensorflow.org/tfrc/) program.
It still costs a few hundred dollars to run a virtual machine and use the cloud storage, though.

**Comment by sezai-rdc** [comment]
Thank you!
My last question is, how do you convert to the pytorch model?
Did you use transformers's "convert_bert_original_tf_checkpoint_to_pytorch.py"?

**Comment by singletongue** [comment]
Sorry for leaving the last question unanswered.

Yes, I used `convert_bert_original_tf_checkpoint_to_pytorch.py` to convert the models.
