### ISSUE TITLE
What is the size (GB) of the pretraining corpus?

### ISSUE THREAD

**Issue by ciwang** [cl-tohoku/bert-japanese#21]
I couldn't find the ja-wiki dump used to train the language model. Is it accessible anywhere and how large is it (in GB, tokens, etc.)?

**Comment by singletongue** [comment]
The text files we used for the training are 2.6GB in total, consisting of approximately 17M sentences.
Unfortunately, the dump file we used is no longer available for download.

**Comment by ciwang** [comment]
Thank you!

**Comment by keleog** [comment]
@ciwang did you manage to obtain the data by any other means pls?
