### ISSUE TITLE
Please tell us how to quote your model for paper

### ISSUE THREAD

**Issue by nakamolinto** [cl-tohoku/bert-japanese#27]
Thank  you for your great job. I am writing international workshop paper, and I would like
to quote your pretrained japanese model(I used in it) . If you did not set how to quote yet , please check below sample is OK or not. 
```Suzuki Masatoshi(2019) Pretrained Japanese BERT models, GitHub, GitHub repository, https://github.com/cl-tohoku/bert-japanese```
Thank you for your help.

**Comment by singletongue** [comment]
Hi, @nakamolinto 

Thank you for citing us!
There is no problem in your sample reference.
It is also OK to just add a footnote referring to the URL of this repository, rather than creating a bibliography item.

Thank you.

**Comment by nakamolinto** [comment]
@singletongue 
Thank you for your quick reply! Thank you for checking my sample.

>It is also OK to just add a footnote referring to the URL
OK, I will follow the paper instruction, and choose.

Thank you for your great job.
Regards
