### ISSUE TITLE
Could not download jawiki-20230102

### ISSUE THREAD

**Issue by Judyyyyy-L** [cl-tohoku/bert-japanese#37]
Was about to do the comparision experiment, 
however, I could not download the jawiki-20230102 version.

Could you kindly share this wiki data with me?

Much appreciation.

**Comment by singletongue** [comment]
Hi, @zhutixiaojie0120.

Thank you for your interest in our experiments.
We would like to share the dump file, but it is too large to share on GitHub (about 10 GB).
We are seeking the way of sharing the file appropriately. 
We will let you know when we are ready to share the file.

Thank you for your patience.

**Comment by Judyyyyy-L** [comment]
@singletongue 
Thank you so much for your kind reply.
I will wait for it!

**Comment by singletongue** [comment]
We have made the dump file temporarily available at https://www.nlp.ecei.tohoku.ac.jp/projects/bert-japanese/.
Please refer to [this page](https://dumps.wikimedia.org/legal.html) for the license information of the file.

When you finished downloading the file, please notify us by replying to this issue.

Thank you.

**Comment by Judyyyyy-L** [comment]
@singletongue 
I have downloaded the wiki dump file you provided.
I will read the license of Wiki and also the license of bert-japanese from Tohoku University before taking any actions which may involve the public usage.

Thank you so much for your quick response and kind support.
Please let me close this issue.

Again, much appreciation!
