### ISSUE TITLE
How to use my own pretrained model?

### ISSUE THREAD

**Issue by YosukeHiguchi** [cl-tohoku/bert-japanese#5]
I followed "Details of pretraining" and have pretrained a model using my own dataset. Could you tell me how to convert the model files (model.ckpt*) so that the model can be used in Transformers library? I will appreciate your help with my problem.

**Comment by singletongue** [comment]
With the latest Transformers (v2.3.0) installed, you can convert models with a command like this:

```sh
transformers-cli convert --model_type bert --tf_checkpoint model.ckpt --pytorch_dump_output pytorch_model.bin --config config.json
```

[The source code](https://github.com/huggingface/transformers/blob/master/src/transformers/commands/convert.py) may also be helpful.

**Comment by YosukeHiguchi** [comment]
Thank you for your advices!!
