### ISSUE TITLE
Is it unnecessary to use neologd in segmentation?

### ISSUE THREAD

**Issue by freshell** [cl-tohoku/bert-japanese#6]
I'm using your pretrained model via huggingface transformers.
In Details of pretraining, neologd is used, whereas Requirements demands only mecab-python3 install, that is it is just original ipadic. 
Its different may be small by wordpiece/BPE, but not exactly same, I think.

**Comment by singletongue** [comment]
We use NEologd just for sentence segmentation when preparing one-sentence-per-line corpus files.
The segmentation of words are done with the original ipadic.

**Comment by freshell** [comment]
Thank you for quick response!
I was misunderstanding. I understood your model could be used with only ipadic.
However I recognized neologd is necessary in preprocess before tokenization.
