### ISSUE TITLE
License for models

### ISSUE THREAD

**Issue by MobiusLooper** [cl-tohoku/bert-japanese#7]
Hi!

First off, thanks a lot for making and sharing these models.

Second, is there a license that can be applied to the pre-trained models themselves?

Thanks,
Josh

**Comment by singletongue** [comment]
The pretrained models are distributed under CC-BY-SA license, as they are trained on Wikipedia.

I've just updated README. Thank you for your comment!
https://github.com/cl-tohoku/bert-japanese#licenses

**Comment by MobiusLooper** [comment]
Thanks @singletongue!
